version: "3"

services:
  mongo:
    container_name: telegram-mongo
    image: mongo:latest
    command: mongod --port ${MONGODB_PORT:-27018}
    restart: always
    env_file:
      - config/config.env
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27018}:${MONGODB_PORT:-27018}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: telegram-bot
    command: python3 bot/bot.py
    restart: always
    env_file:
      - config/config.env
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./:/app
    extra_hosts:
      - "firecrawl-pi:10.0.0.107"

  mongo_express:
    container_name: telegram-mongo-express
    image: mongo-express:latest
    restart: always
    env_file:
      - config/config.env
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8082}:${MONGO_EXPRESS_PORT:-8082}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27018}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
