
telegram_token: ""

azure_api_key: ""
azure_api_base: ""
azure_chatapi_version: ""
azure_embeddingapi_version: ""

###############################################
# Generic LLM role mappings (replaces gpt4/gpt35 specific names)
# Fill in only what you use.
###############################################
smart_llm_azure_deployment: ""      # ex: gpt-4 or gpt-4o
smart_llm_openai_model: ""          # ex: gpt-4o-2024-05-13
thinking_llm_azure_deployment: ""   # ex: gpt-4.1
thinking_llm_openai_model: ""       # ex: gpt-4.1
fast_llm_azure_deployment: ""       # ex: gpt-4o-mini
fast_llm_openai_model: ""           # ex: gpt-4o-mini-2024-07-18
superfast_llm_azure_deployment: ""  # ex: gpt-5-nano (ultra fast)
embedding_azure_deployment: ""      # ex: text-embedding-3-small
embedding_openai_model: ""          # ex: text-embedding-3-small

ollama_api_key: ""
ollama_api_base: ""

rvctts_api_base: ""

# Bing Search
bing_api_key: ""
bing_endpoint: ""

# Firecrawl self-hosted search
firecrawl_base_url: "http://localhost:3002"
firecrawl_api_key: "fc-YOUR_API_KEY"

# Gemini
google_api_key: ""
gemini_model_name: ""

# Cohere
cohere_api_key: ""

# Groq
groq_api_key: ""

# weather agent
openweather_api_key: ""

azurespeechkey: ""
azurespeechregion: ""
azuretexttranslatorkey: ""
use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
enable_message_streaming: true  # if set, messages will be shown to user word-by-word

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006

paths:
  UPLOAD_FOLDER: ""
  BING_FOLDER: ""
  SUMMARY_FOLDER: ""
  VECTOR_FOLDER: ""

settings:
  temperature: 0.25
  max_tokens: 420
  model_name: ""
  num_output: 1024
  max_chunk_overlap_ratio: 0.1
  max_input_size: 128000
  context_window: 128000
