available_text_models: ["gpt-5-chat", "gpt-5", "model-router", "gemini-2.5-flash"]

info:

  gpt-5-chat:
    type: chat_completion
    name: GPT-5 Chat
    description: High‑conversation fidelity chat-optimized GPT‑5 variant. Tuned for multi‑turn dialogue, tool calling, and low hallucination rate. (Provisional metadata – adjust when official specs confirmed.)
    price_per_1000_input_tokens: 0.010  # Placeholder; update with official pricing
    price_per_1000_output_tokens: 0.030 # Placeholder; update with official pricing
    scores:  # Relative, 1–5 scale
      Smart: 5
      Fast: 4
      Cheap: 3

  gpt-5:
    type: chat_completion
    name: GPT-5
    description: General-purpose GPT‑5 base model for reasoning, coding, and complex analytical tasks. (Provisional metadata – update once finalized.)
    price_per_1000_input_tokens: 0.012  # Placeholder
    price_per_1000_output_tokens: 0.036 # Placeholder
    scores:
      Smart: 5
      Fast: 3
      Cheap: 2

  model-router:
    type: chat_completion
    name: model-router
    description: Dynamically selects an optimal underlying model per request (cost, latency, complexity). Pricing reflects averaged/estimated blended usage; adjust to your deployment.
    price_per_1000_input_tokens: 0.003  # Approximate/placeholder
    price_per_1000_output_tokens: 0.004 # Approximate/placeholder
    scores:
      Smart: 3
      Fast: 4
      Cheap: 5

  gemini-2.5-flash:
    type: chat_completion
    name: Gemini 2.5 Flash
    description: Fast multimodal Gemini Flash 2.5 variant supporting text, images, and lightweight audio. Suited for low‑latency, high‑throughput tasks.
    price_per_1000_input_tokens: 0.00015 # Non-thinking tier
    price_per_1000_output_tokens: 0.0006  # Non-thinking tier
    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  # Non-text models (retained)
  dall-e-3:
    type: image
    price_per_1_image: 0.040

  gpt-image-1:
    type: image
    name: GPT-Image-1
    description: Advanced image generation & editing (in/out-paint, image-to-image). High fidelity and prompt adherence.
    price_per_1_image: 0.170  # Placeholder/estimated
    scores:
      Smart: 5
      Fast: 1
      Cheap: 1

  whisper:
    type: audio
    price_per_1_min: 0.006
